<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Service2" targetNamespace="urn:com.example.switchyard:sy_transformer:1.0" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:com.example.switchyard:sy_transformer:1.0" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:com.example.switchyard:sy_transformer:1.0" attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="urn:com.example.switchyard:sy_transformer:1.0">
  <xs:complexType name="object2">
    <xs:sequence/>
  </xs:complexType>
  <xs:element name="invoke" type="invoke"/>
  <xs:complexType name="invoke">
    <xs:sequence>
      <xs:element minOccurs="0" name="object2" type="object2"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="invokeResponse" type="invokeResponse"/>
  <xs:complexType name="invokeResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="object2" type="object2"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>
  </wsdl:types>
  <wsdl:message name="invoke">
    <wsdl:part name="parameters" element="tns:invoke">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="invokeResponse">
    <wsdl:part name="parameters" element="tns:invokeResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Service2PortType">
    <wsdl:operation name="invoke">
      <wsdl:input name="invoke" message="tns:invoke">
    </wsdl:input>
      <wsdl:output name="invokeResponse" message="tns:invokeResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="Service2SoapBinding" type="tns:Service2PortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="invoke">
      <soap:operation soapAction="invoke" style="document"/>
      <wsdl:input name="invoke">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="invokeResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Service2">
    <wsdl:port name="Service2Port" binding="tns:Service2SoapBinding">
      <soap:address location="http://localhost:8080/sy_transformer/Service2"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
